// Auto-generated by Supabase — DO NOT EDIT MANUALLY
// Regenerate with: npm run db:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      agent_runs: {
        Row: {
          error: string | null
          finished_at: string | null
          id: string
          input: Json | null
          result: Json | null
          shop_id: string
          started_at: string
          status: string
          steps: Json
          trigger_ref_id: string | null
          trigger_type: string
        }
        Insert: {
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          result?: Json | null
          shop_id: string
          started_at?: string
          status?: string
          steps?: Json
          trigger_ref_id?: string | null
          trigger_type: string
        }
        Update: {
          error?: string | null
          finished_at?: string | null
          id?: string
          input?: Json | null
          result?: Json | null
          shop_id?: string
          started_at?: string
          status?: string
          steps?: Json
          trigger_ref_id?: string | null
          trigger_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "agent_runs_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      call_extractions: {
        Row: {
          call_id: string
          car_details: Json | null
          created_at: string
          estimated_severity: string | null
          id: string
          issue_description: string | null
          person_email: string | null
          person_name: string | null
          person_phone: string | null
        }
        Insert: {
          call_id: string
          car_details?: Json | null
          created_at?: string
          estimated_severity?: string | null
          id?: string
          issue_description?: string | null
          person_email?: string | null
          person_name?: string | null
          person_phone?: string | null
        }
        Update: {
          call_id?: string
          car_details?: Json | null
          created_at?: string
          estimated_severity?: string | null
          id?: string
          issue_description?: string | null
          person_email?: string | null
          person_name?: string | null
          person_phone?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "call_extractions_call_id_fkey"
            columns: ["call_id"]
            isOneToOne: false
            referencedRelation: "calls"
            referencedColumns: ["id"]
          },
        ]
      }
      calls: {
        Row: {
          created_at: string
          customer_id: string | null
          direction: string
          ended_at: string | null
          id: string
          raw_payload: Json | null
          shop_id: string
          started_at: string | null
          status: string
          transcript: string | null
          vapi_call_id: string | null
        }
        Insert: {
          created_at?: string
          customer_id?: string | null
          direction?: string
          ended_at?: string | null
          id?: string
          raw_payload?: Json | null
          shop_id: string
          started_at?: string | null
          status?: string
          transcript?: string | null
          vapi_call_id?: string | null
        }
        Update: {
          created_at?: string
          customer_id?: string | null
          direction?: string
          ended_at?: string | null
          id?: string
          raw_payload?: Json | null
          shop_id?: string
          started_at?: string | null
          status?: string
          transcript?: string | null
          vapi_call_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "calls_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "calls_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      customers: {
        Row: {
          created_at: string
          email: string | null
          id: string
          name: string | null
          notes: string | null
          phone: string | null
          plate: string | null
          shop_id: string
          vehicle_make: string | null
          vehicle_model: string | null
          vehicle_year: number | null
        }
        Insert: {
          created_at?: string
          email?: string | null
          id?: string
          name?: string | null
          notes?: string | null
          phone?: string | null
          plate?: string | null
          shop_id: string
          vehicle_make?: string | null
          vehicle_model?: string | null
          vehicle_year?: number | null
        }
        Update: {
          created_at?: string
          email?: string | null
          id?: string
          name?: string | null
          notes?: string | null
          phone?: string | null
          plate?: string | null
          shop_id?: string
          vehicle_make?: string | null
          vehicle_model?: string | null
          vehicle_year?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "customers_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      followups: {
        Row: {
          calendar_event_id: string | null
          created_at: string
          customer_id: string
          id: string
          notes: string | null
          scheduled_at: string | null
          shop_id: string
          status: string
          type: string
        }
        Insert: {
          calendar_event_id?: string | null
          created_at?: string
          customer_id: string
          id?: string
          notes?: string | null
          scheduled_at?: string | null
          shop_id: string
          status?: string
          type: string
        }
        Update: {
          calendar_event_id?: string | null
          created_at?: string
          customer_id?: string
          id?: string
          notes?: string | null
          scheduled_at?: string | null
          shop_id?: string
          status?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "followups_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "followups_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      quotes: {
        Row: {
          call_id: string | null
          created_at: string
          customer_id: string
          gmail_message_id: string | null
          id: string
          line_items: Json
          sent_at: string | null
          sent_via: string | null
          shop_id: string
          status: string
          subtotal: number
          tax: number
          total: number
        }
        Insert: {
          call_id?: string | null
          created_at?: string
          customer_id: string
          gmail_message_id?: string | null
          id?: string
          line_items?: Json
          sent_at?: string | null
          sent_via?: string | null
          shop_id: string
          status?: string
          subtotal?: number
          tax?: number
          total?: number
        }
        Update: {
          call_id?: string | null
          created_at?: string
          customer_id?: string
          gmail_message_id?: string | null
          id?: string
          line_items?: Json
          sent_at?: string | null
          sent_via?: string | null
          shop_id?: string
          status?: string
          subtotal?: number
          tax?: number
          total?: number
        }
        Relationships: [
          {
            foreignKeyName: "quotes_call_id_fkey"
            columns: ["call_id"]
            isOneToOne: false
            referencedRelation: "calls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "quotes_shop_id_fkey"
            columns: ["shop_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id"]
          },
        ]
      }
      shops: {
        Row: {
          business_hours: Json | null
          created_at: string
          google_calendar_id: string | null
          google_email: string | null
          google_refresh_token_encrypted: string | null
          human_redirect_number: string | null
          id: string
          name: string
          onboarding_status: string
          owner_user_id: string
          phone_number: string | null
          phone_provisioning_type: string | null
          pricing_config: Json | null
          vapi_assistant_id: string | null
          vapi_phone_number_id: string | null
        }
        Insert: {
          business_hours?: Json | null
          created_at?: string
          google_calendar_id?: string | null
          google_email?: string | null
          google_refresh_token_encrypted?: string | null
          human_redirect_number?: string | null
          id?: string
          name: string
          onboarding_status?: string
          owner_user_id: string
          phone_number?: string | null
          phone_provisioning_type?: string | null
          pricing_config?: Json | null
          vapi_assistant_id?: string | null
          vapi_phone_number_id?: string | null
        }
        Update: {
          business_hours?: Json | null
          created_at?: string
          google_calendar_id?: string | null
          google_email?: string | null
          google_refresh_token_encrypted?: string | null
          human_redirect_number?: string | null
          id?: string
          name?: string
          onboarding_status?: string
          owner_user_id?: string
          phone_number?: string | null
          phone_provisioning_type?: string | null
          pricing_config?: Json | null
          vapi_assistant_id?: string | null
          vapi_phone_number_id?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_shop_owner: { Args: { p_shop_id: string }; Returns: boolean }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

// Convenience row types
export type Shop = Database['public']['Tables']['shops']['Row']
export type Customer = Database['public']['Tables']['customers']['Row']
export type Call = Database['public']['Tables']['calls']['Row']
export type CallExtraction = Database['public']['Tables']['call_extractions']['Row']
export type Quote = Database['public']['Tables']['quotes']['Row']
export type AgentRun = Database['public']['Tables']['agent_runs']['Row']
export type Followup = Database['public']['Tables']['followups']['Row']

// Business-domain types parsed from JSON columns
export interface LineItem {
  description: string
  qty: number
  unit_price: number
}

export interface CarDetails {
  make?: string
  model?: string
  year?: number
  plate?: string
  vin?: string
}

export interface BusinessHours {
  mon?: { open: string; close: string }
  tue?: { open: string; close: string }
  wed?: { open: string; close: string }
  thu?: { open: string; close: string }
  fri?: { open: string; close: string }
  sat?: { open: string; close: string }
  sun?: { open: string; close: string }
}

export interface CommonService {
  name: string
  labor_hours: number
  parts_cost: number
}

export interface PricingConfig {
  labor_rate?: number
  parts_markup?: number
  tax_rate?: number
  common_services?: CommonService[]
}

export interface AgentStep {
  step: number
  tool: string
  input: unknown
  output: unknown
  duration_ms: number
  status: 'success' | 'error'
  error?: string
}
